__version__ = "2.12.0a6"
__title__ = "cybsi-python-sdk"
__description__ = "Cybersecurity threat intelligence development kit"
__license__ = "Apache License 2.0"
__author__ = "Cybsi SDK Developers"
__author_email__ = ""
